### ISSUE TITLE
Schema4.Items not working as expected

### ISSUE THREAD

**Issue by vamsitp** [NJsonSchema/NJsonSchema#32] opened 2016-03-03 08:03 UTC
[NJsonSchemaItemsTest.zip](https://github.com/NJsonSchema/NJsonSchema/files/156347/NJsonSchemaItemsTest.zip)
Attached is a recursive test that compares how NewtonSoft can get hold of all Properties and Items for a given Schema, while NJsonSchema does not get the Items' properties...

**Schema:**
```
{
  "typeName": "ClassRoom",
  "additionalProperties": false,
  "type": "object",
  "required": [
    "Id"
  ],
  "properties": {
    "Id": {
      "type": "integer"
    },
    "Name": {
      "type": "string"
    },
    "Size": {
      "type": [ "integer", "null" ]
    },
    "Students": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Age": {
            "type": [ "integer", "null" ]
          },
          "Name": {
            "type": [ "string", "null" ]
          }
        }
      }
    }
  },
  "$schema": "http://json-schema.org/draft-04/schema#"
}
```

**Output of the test:**
```
NJsonSchema - Properties >> Items:
NJsonSchema Property: Id
NJsonSchema Property: Name
NJsonSchema Property: Size
NJsonSchema Property: Students

Newtonsoft.Json.Schema - Properties >> Items:
Newtonsoft Property: Id
Newtonsoft Property: Name
Newtonsoft Property: Size
Newtonsoft Property: Students
*Newtonsoft Item:  |
Newtonsoft Property: Age
Newtonsoft Property: Name*
```

**Comment by rsuter** [comment] 2016-03-03 08:13
If only a single schema is defined for an array, then you have to access it with the `Item` property instead of the `Items` property. See

https://github.com/NJsonSchema/NJsonSchema/blob/master/src/NJsonSchema/JsonSchema4.Serialization.cs#L78

**Comment by rsuter** [comment] 2016-03-03 08:16
The question here is whether these two properties should be merged together (as you originally expected). 

The drawback is that a collection with a single item will be automatically converted to a single schema (without array) and thus as conversion roundtrip (i.e. deserialize schema => serialize schema) may fail (i.e. not the same output).

**Comment by vamsitp** [comment] 2016-03-03 08:22
Even if there is a single schema defined for an array, shouldn't Item be part of the Items property ideally (Items will just return the single Item in the collection like NewtonSoft does)?

**Comment by rsuter** [comment] 2016-03-03 08:26
We could Item change so that it only modifies the Items property and sets or removes its collection with one item...

**Comment by rsuter** [comment] 2016-03-03 08:27
And what returns Item when Items contains multiple items?

**Comment by vamsitp** [comment] 2016-03-03 08:28
Just remove the _Item _ property to avoid confusion? Just have Items (for either single or more items).

**Comment by vamsitp** [comment] 2016-03-03 09:31
Regarding your comment:
> > The drawback is that a collection with a single item will be automatically converted to a single schema (without array) and thus as conversion roundtrip (i.e. deserialize schema => serialize schema) may fail (i.e. not the same output).

**With NJsonSchema:**
`Console.WriteLine(JsonConvert.SerializeObject(njsonSchema, Formatting.Indented));
{
  "typeName": "ClassRoom",
  "additionalProperties": false,
  "type": "object",
  "required": [
    "Id"
  ],
  "properties": {
    "Id": {
      "type": "integer"
    },
    "Name": {
      "type": "string"
    },
    "Size": {
      "type": [
        "integer",
        "null"
      ]
    },
    "Students": {
      "items": {
        "type": "object",
        "properties": {
          "Age": {
            "type": [
              "integer",
              "null"
            ]
          },
          "Name": {
            "type": [
              "null",
              "string"
            ]
          }
        }
      },
      "type": "array"
    }
  },
  "$schema": "http://json-schema.org/draft-04/schema#"
}`

**While with Newtonsoft Schema:**
`Console.WriteLine(JsonConvert.SerializeObject(jsonNetSchema, Formatting.Indented));
{
  "typeName": "ClassRoom",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "Id": {
      "type": "integer"
    },
    "Name": {
      "type": "string"
    },
    "Size": {
      "type": [
        "integer",
        "null"
      ]
    },
    "Students": {
     ** "type": "array",
**      "items": {
        "type": "object",
        "properties": {
          "Age": {
            "type": [
              "integer",
              "null"
            ]
          },
          "Name": {
            "type": [
              "string",
              "null"
            ]
          }
        }
      }
    }
  },
  "required": [
    "Id"
  ]
}`

**Comment by vamsitp** [comment] 2016-03-03 11:34
Actually, both of them have the Type:Array retained. Updated the formatting above. So it should not be a problem moving Item to Items?

**Comment by rsuter** [comment] 2016-03-03 12:08
(Please use three ` at the beginning and end of source code blocks here so that they are formatted correctly)

**Comment by rsuter** [comment] 2016-03-03 12:10
The output of both libraries is correct: Only the `items` is allowed on the JSON Schema... NJsonSchema introduces the `Item` property for better access/readability

**Comment by vamsitp** [comment] 2016-03-03 12:20
Yeah, so would be populating _Items _too now (even if there's a single _Item_)?

**Comment by rsuter** [comment] 2016-03-03 12:49
As you can see here: 

http://spacetelescope.github.io/understanding-json-schema/reference/array.html

the two properties cannot be merge because 

    Item = Schema 

is not the same as 

    Items = new List { Schema }

This is because the Item schema validates every item in the array and Items validates a tuple...

**Comment by vamsitp** [comment] 2016-03-03 13:36
All I'm saying is the **Type** of the property should decide how it's interpreted/represented. If I declare a **Type **as an **Array**, I'd expect it back in a collection (**Items**). It's confusing when we declare something as an array, but have to probe the **Item **property instead of **Items **. In the above example, what I've been using so far with NewtonSoft is property.Items to fetch properties recursively of all Items (since I declared Students as an **Array**). With NJsonSchema, I need to first check if **Item != null**, else, probe **Items**. Not a big deal, but a bit confusing...

**Comment by rsuter** [comment] 2016-03-03 13:47
Yes, but the semantics is different: 

- Item: Array with uniform items (all have the same schema)
- Items: Tuple array with different items

Having Item and Items with one schema is not the same and thus we need both... How does Json.NET solve this problem?

**Comment by vamsitp** [comment] 2016-03-03 17:34
NewtonSoft: ```IList<JSchema> Items```. (did not look into the details)
In NJsonSchema case, If **Item** was an array like you said, it would have been nice (but probably more confusing :-)), but it's just an instance of type ```JsonSchema4``` - right?

**Comment by rsuter** [comment] 2016-03-03 17:41
The problem is, that the validator has to differentiate between a single item and a list with a single item and this is not possible with a single list property... 
The only way to solve this is to make the `Items` property of type `object` so that assigning a schema or a list of schemes are allowed...

**Comment by vamsitp** [comment] 2016-03-03 17:45
Yeah, that is what I was about to say...In example from the link above, setting the ```Type``` to ```object``` (instead of number) would mean I can have different objects with different properties (which is what I have currently and NewtonSoft is handling fine)...

```{
  "type": "array",
  "items": {
    "type": "object"
  }
}```

**Comment by rsuter** [comment] 2016-03-03 18:00
Yes, but this should work with NJsonSchema too if you set the `Item` property...

**Comment by rsuter** [comment] 2016-03-03 18:02
Just to complete this. 

Schema 

    { "type": "array", "items": { "type": "number" } }  

Data: 

    [5, true]

INVALID

Schema

    { "type": "array", "items": [{ "type": "number" }] }  

Data: 

    [5, true]

VALID

**Comment by vamsitp** [comment] 2016-03-04 05:41
Got you. I guess Newtonsoft conditionally handles it somehow making use of other properties like ```UniqueItems```

**Closed** 2016-05-02 21:39 UTC
Labels: discussion
